[OBMIN-297] Created Toast
Jack11M/obminyashka.space pull request #489
Opened 2023-02-22 17:58 UTC by Kyslytsia

Created Toast

2023-02-24 14:33 UTC, ASGladchenko approved these changes

2023-02-24 14:33 UTC, AkintsevaElizaveta approved these changes

2023-02-24 20:07 UTC, rpkyrych requested changes
You should squash your commits and push force to the branch!!!

2023-03-04 10:43 UTC, rpkyrych approved these changes
Rewritten commits with a single one

2023-03-04 13:59 UTC, Mish-hash approved these changes

2023-03-04 14:34 UTC, Wolshebnik requested changes

2023-03-04 14:34 UTC, Wolshebnik commented on src/main/resources/react/src/components/common/index.js
>  export { showPassword } from './show-password';
I think you should delete showPassword from EVO

2023-03-04 14:34 UTC, Wolshebnik commented on src/main/resources/react/src/pages/AddGoods/location/index.jsx
>  /* eslint-disable indent */
try to delete this line

2023-03-04 15:29 UTC, Kyslytsia commented on src/main/resources/react/src/pages/AddGoods/location/index.jsx
>  /* eslint-disable indent */
if i remove this line i get errors

2023-03-04 16:06 UTC, Wolshebnik commented on src/main/resources/react/src/pages/AddGoods/location/index.jsx
>  /* eslint-disable indent */
sorry, I understood

2023-03-04 16:07 UTC, Wolshebnik approved these changes

2023-03-04 16:09 UTC, merged