Obmin 318 chenge select language component
Jack11M/obminyashka.space pull request #524
Opened 2023-03-14 21:45 UTC by Mish-hash

2023-03-16 21:50 UTC, Wolshebnik approved these changes

2023-03-16 21:51 UTC, Wolshebnik requested changes

2023-03-16 21:51 UTC, Wolshebnik commented on package-lock.json
delete this file
you try to do npm i in main path

2023-03-17 11:12 UTC, Wolshebnik approved these changes

2023-03-17 11:59 UTC, cloudmenson approved these changes

2023-03-17 12:10 UTC, Voloshkina approved these changes

2023-03-18 16:00 UTC, Viktoria-Serkiz approved these changes

2023-03-18 16:00 UTC, Kyslytsia approved these changes

2023-03-18 17:07 UTC, merged