[hotfix/OBMIN-210] creat query for OAuth2 account
Jack11M/obminyashka.space pull request #525
Opened 2023-03-15 00:03 UTC by Sershok

set flag true if accont created long time ago

2023-03-15 08:13 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/impl/UserServiceImpl.java
> +        optionalUser.ifPresent(user -> userRepository.setOAuth2LoginToUserByEmail(oauth2User.getEmail()));
You don't use **user** in the body of optional so just rename it to "**ignored**.

The new behaviour in **loginUserWithOAuth2** has to be covered at least with a unit test

2023-03-15 08:13 UTC, rpkyrych approved these changes
A new unit test is required

2023-03-16 14:35 UTC, rpkyrych approved these changes

2023-03-17 07:24 UTC, rpkyrych requested changes
The test class shouldn't use the context

2023-03-17 07:24 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceTest.java
> +@SpringBootTest
You shouldn't use that annotation. It uses the context

2023-03-17 07:24 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceTest.java
> +    @MockBean
You should use Mock annotation instead

2023-03-17 07:24 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceTest.java
> +    @Autowired
InjectMocks should be used instead

2023-03-17 16:14 UTC, ennnbaev approved these changes
Great!

2023-03-17 16:16 UTC, rpkyrych approved these changes

2023-03-17 16:37 UTC, ImAndVlad approved these changes

2023-03-17 17:31 UTC, IllyaZuew approved these changes

2023-03-17 18:29 UTC, demus-n approved these changes

2023-03-17 20:19 UTC, merged