OBMIN-343 Solved TODOs
Jack11M/obminyashka.space pull request #535
Opened 2023-03-22 16:42 UTC by ennnbaev

OBMIN-343 Solved TODOs by this link https://github.com/Jack11M/obminyashka.space/pull/527/files#r1137373950

2023-03-23 15:07 UTC, IllyaZuew submitted a review, later dismissed

2023-03-23 16:32 UTC, ImAndVlad submitted a review, later dismissed

2023-03-23 17:43 UTC, IllyaZuew submitted a review, later dismissed

2023-03-24 10:26 UTC, Sershok submitted a review, later dismissed

2023-03-24 11:54 UTC, demus-n approved these changes

2023-03-24 14:59 UTC, rpkyrych requested changes
A small polishing is needed as the final step

2023-03-24 14:59 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/controller/request/AdvertisementFindThumbnailsRequest.java
> +public class AdvertisementFindThumbnailsRequest {
You can omit **Thumbnails** from the name because that would be the return parameter of the requested endpoint

2023-03-24 14:59 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/controller/request/AdvertisementFindThumbnailsRequest.java
> +    private Long subcategoryId;
I would ask you to put Nullable annotation above that parameter and excludeAdvertisementId. They would allow us not to miss that case

2023-03-24 14:59 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/dto/CategoryNameDto.java
> +    @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
👍

2023-03-24 14:59 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/AdvertisementService.java
> +    Page<AdvertisementTitleDto> findAllThumbnails(AdvertisementFindThumbnailsRequest advertisementFindThumbnailsRequest);
the name of the variable can be shortened to **findAdvsRequest** or **findRequest**

2023-03-24 14:59 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
> +                .countByIdNotAndSubcategoryId(advertisementFindThumbnailsRequest.getExcludeAdvertisementId(), advertisementFindThumbnailsRequest.getSubcategoryId());
Just make it shorted **advertisementFindThumbnailsRequest** variable name and if you need to split the code do it after the first bracket

2023-03-24 14:59 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/impl/AdvertisementServiceImpl.java
> +    public Page<AdvertisementTitleDto> findAllThumbnails(AdvertisementFindThumbnailsRequest advertisementFindThumbnailsRequest) {
The variable name can be shortened

2023-03-24 16:29 UTC, rpkyrych approved these changes

2023-03-24 16:43 UTC, IllyaZuew approved these changes

2023-03-24 17:36 UTC, Sershok approved these changes

2023-03-24 17:46 UTC, ImAndVlad approved these changes

2023-03-24 18:34 UTC, demus-n approved these changes

2023-03-24 18:48 UTC, merged