OBMIN-344 new service for receiving the validation code
Jack11M/obminyashka.space pull request #537
Opened 2023-03-24 15:52 UTC by Sershok

Created new service for receiving the validation code

1.  created methods **validateEmail()** in MailService
2.  add new column **validatedEmail** in User 
3.  created unit test **EmailServiceTest**

2023-03-24 16:30 UTC, IllyaZuew commented on src/main/java/space/obminyashka/items_exchange/service/MailService.java
>       * @throws IOException when service is unavailable or some unexpected case happened
The same problem with spaces

2023-03-24 16:30 UTC, IllyaZuew commented on src/main/java/space/obminyashka/items_exchange/service/impl/SendGridService.java
> +        }
will be good to rewrite it without using if but it only my opinion

2023-03-24 16:30 UTC, IllyaZuew commented on src/test/java/space/obminyashka/items_exchange/service/EmailServiceTest.java
> +        when(emailConfirmationTokenRepository.findById(UUID.fromString("61731cc8-8104-49f0-b2c3-5a52e576ab18")))
you should create variable for UUID and use it

2023-03-24 16:30 UTC, IllyaZuew commented on src/test/java/space/obminyashka/items_exchange/service/EmailServiceTest.java
> +        user.setId(UUID.fromString("61731cc8-8104-49f0-b2c3-5a52e576ab18"));
you should create variable for UUID and use it like string

2023-03-25 11:21 UTC, IllyaZuew commented on src/test/java/space/obminyashka/items_exchange/service/EmailServiceTest.java
> +}
you should write tests for exceptions and maybe you can do it like parameterized test

2023-03-25 11:24 UTC, IllyaZuew commented on src/test/java/space/obminyashka/items_exchange/service/EmailServiceTest.java
> +}
you check only successful result but you need to check and bad results with exceptions

2023-04-03 17:33 UTC, IllyaZuew commented on src/test/java/space/obminyashka/items_exchange/service/EmailServiceTest.java
> +    void shouldThrowEmailValidationCodeNotFoundException() {
make name with patern method_when_should

2023-04-03 17:33 UTC, IllyaZuew commented on src/test/java/space/obminyashka/items_exchange/service/EmailServiceTest.java
> +    void shouldThrowEmailValidationCodeExpiredException() {
make name with patern method_when_should

2023-04-03 18:42 UTC, IllyaZuew approved these changes

2023-04-04 19:46 UTC, IllyaZuew approved these changes

2023-04-05 10:35 UTC, ennnbaev approved these changes

2023-04-05 10:52 UTC, demus-n submitted a review, later dismissed

2023-04-05 12:25 UTC, ImAndVlad approved these changes

2023-04-05 14:08 UTC, rpkyrych requested changes
Some parts need to be changed.

2023-04-05 14:08 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/dao/UserRepository.java
> +    void setValidatedEmailToUserById(UUID id);
We shouldn't expose users' ID outside. That method have to work with EmailConfirmationCode ID instead

2023-04-05 14:08 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/impl/SendGridService.java
> +    private final EmailConfirmationCodeRepository emailConfirmationCodeRepository;
The same class is introduced on line 38

2023-04-05 14:08 UTC, rpkyrych commented on src/main/resources/liquibase/db.changelog-1.2.xml
> +    </changeSet>
Don't you mind making all those changes by a single changeset?

2023-04-06 15:36 UTC, closed without merging