OBMIN-334 Validation of incoming validation code for 24-hour expiration
Jack11M/obminyashka.space pull request #543
Opened 2023-04-01 17:24 UTC by IllyaZuew

changes:
*add creating of validation code when user successfully registered
*add expiration time for validation code
*write tests

2023-04-03 08:35 UTC, ImAndVlad submitted a review, later dismissed

2023-04-03 10:43 UTC, ennnbaev commented on src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
>              return new ResponseEntity<>(getMessageSource(ResponseMessagesHandler.ValidationMessage.USER_CREATED), HttpStatus.CREATED);
You should use service to save token

2023-04-03 10:43 UTC, ImAndVlad submitted a review, later dismissed

2023-04-03 10:48 UTC, Sershok approved these changes

2023-04-03 11:03 UTC, ennnbaev submitted a review, later dismissed

2023-04-03 11:10 UTC, demus-n submitted a review, later dismissed

2023-04-03 15:38 UTC, rpkyrych requested changes

2023-04-03 15:38 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
> +    private int numberOfHoursToKeepEmailConformationToken;
Make it final and add Value annotation into Lombok's configuration

2023-04-03 15:38 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
> +        EmailConfirmationToken token = new EmailConfirmationToken(null, UUID.randomUUID().toString(),
Why not to edit a constructor instead of passing null?
The variable has to be as much closer to its invocation as possible.

2023-04-03 15:38 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
> +            token.setUser(userService.findByUsernameOrEmail(userRegistrationDto.getEmail()).get());
That is excess call to the DB. Would you mind using existing logic or update it for your needs instead of making an additional call?

2023-04-03 15:38 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/controller/AuthController.java
> +            confirmationTokenRepository.save(token);
You shouldn't invoke the repository directly from the controller - do it via service.

2023-04-03 15:38 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/AuthorizationControllerTest.java
> +    private User userFromDto = new User();
Why the blank user is created directly here instead of doing that via BeforeEach method?

2023-04-03 15:38 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/AuthorizationControllerTest.java
> +        BeanUtils.copyProperties(dto, userFromDto);
By doing that you make it more difficult to support tests in the future. You should move that part, if it's needed to a specific test / tests which using it

2023-04-03 15:38 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/AuthorizationFlowTest.java
> +    @ExpectedDataSet(value = "auth/create_token.yml", ignoreCols = {"id", "created", "expiry_date", "token", "user_id"})
The email_confirmation_token has 5 columns and here you're ignoring them all. Why that test should be count as valid?

2023-04-16 12:56 UTC, ImAndVlad submitted a review, later dismissed

2023-04-17 08:18 UTC, ennnbaev submitted a review, later dismissed

2023-04-17 09:30 UTC, demus-n submitted a review, later dismissed

2023-04-17 11:10 UTC, Sershok submitted a review, later dismissed

2023-04-17 14:54 UTC, rpkyrych reviewed
Almost what we need

2023-04-17 14:54 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/model/EmailConfirmationCode.java
> +    public EmailConfirmationCode(UUID id, int expirationHours) {
A constructor with less amount of parameters is always placed above it with bigger ones.
Beside that from the current constructor you can invoke the second one with null as a user parameter.

2023-04-17 14:54 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/impl/UserServiceImpl.java
> +    private final int numberOfHoursToKeepEmailConformationCode;
Nice!

2023-04-17 16:50 UTC, rpkyrych approved these changes

2023-04-17 16:52 UTC, demus-n approved these changes

2023-04-17 16:53 UTC, ImAndVlad approved these changes

2023-04-17 17:10 UTC, Sershok approved these changes

2023-04-17 17:13 UTC, merged