Obmin 331 move add goods description component
Jack11M/obminyashka.space pull request #544
Opened 2023-04-04 14:05 UTC by Kyslytsia

Move add goods description component

2023-04-04 14:07 UTC, ASGladchenko submitted a review, later dismissed

2023-04-04 15:50 UTC, Viktoria-Serkiz approved these changes

2023-04-04 15:50 UTC, Voloshkina submitted a review, later dismissed

2023-04-04 19:08 UTC, Wolshebnik commented on package-lock.json
Are you serious?

2023-04-05 07:54 UTC, Wolshebnik approved these changes

2023-04-05 08:12 UTC, Viktoria-Serkiz submitted a review, later dismissed

2023-04-05 09:19 UTC, Voloshkina approved these changes

2023-04-05 10:51 UTC, cloudmenson approved these changes

2023-04-06 11:29 UTC, Wolshebnik requested changes
add error

2023-04-06 16:59 UTC, Mish-hash submitted a review, later dismissed

2023-04-06 17:16 UTC, Wolshebnik approved these changes

2023-04-06 17:19 UTC, Voloshkina approved these changes

2023-04-06 17:23 UTC, Viktoria-Serkiz approved these changes

2023-04-06 17:26 UTC, Mish-hash approved these changes

2023-04-06 17:40 UTC, merged